### ISSUE TITLE
build process uses localhost for publishing

### ISSUE THREAD

**Issue by littlebigco-dev** [jbrodriguez/hugulp#10]
Hi,

this project is exactly what I was looking for since a couple of months. It is great for development, but once I want to build the site for the production server, it still uses --baseURL=localhost:3000.

I am not a gulp expert, but I guess that the gulp task is always invoked with the drafts=true param causing the above issue. I tried to directly start other gulp tasks like hugulp build:publish, but that does not do the trick. Nothing happens at all.

I don't get any errors, so the install seems to be fine. It is mainly the baseURL that makes some trouble.

**Comment by jbrodriguez** [comment]
hi @adcgn , it should work if you invoke ```hugulp build```.

It should create your site under /public, with the asset pipeline ran.

Let me know if that's not what's happening in your case

**Comment by littlebigco-dev** [comment]
Hi @jbrodriguez , yes, the build results in output in the /public directory. However, it does not use the baseURL specified in the config.toml. It still uses the localhost:3000 that is used with the `hugulp watch` command. I'd add a gulp task afterward to copy everything from the /public directory to the server. But that does not work since all links refer to localhost rather than the production URL. 

The asset pipeline works great. I have some missing semicolons in the JS files which result in some warnings but no errors. The JS is working on localhost, so I don't think that causes the issue, does it?

Where does hugulp take the baseURL from if invoked with `hugulp build`?

I also see all the verbose output from hugo and guess that hugo is invoked with all the parameters that are used for development aka the `hugulp watch` command. It seems to me that this is always the case. I am not that familiar with gulp so that I can check and find the reason for that behaviour myself.

It doesn't matter whether I run `hugulp watch` or `hugulp build`. After all, it uses always the localhost:3000 as baseURL.

**Comment by jbrodriguez** [comment]
you're definitely right @adcgn, thanks for bringing this up !

```hugulp build``` is currently still using baseUrl.

I'll fix this today or tomorrow at the latest !
