### ISSUE TITLE
Are subfolders of assets/img processed?

### ISSUE THREAD

**Issue by jaydreyer** [jbrodriguez/hugulp#12]
For most of my js/css/img files, I have subfolders. So in assets/img I have assets/img/main and img/posts or whatever. When I run `hugulp build` are these files in subfolders being processed? Is it expecting a flat structure?

Looking at the code I see `return gulp.src('assets/img/*.*')`, which leads me to think it would just take everything at root. I'm wondering if it was `assets/img/**/*.*` if that would take care of grabbing all files in subdirectories.

**Comment by jbrodriguez** [comment]
That's right, currently it's expecting a flat structure.

Your solution will work.

I'll incorporate it in the next release and for other folders.
