### ISSUE TITLE
Add support for watching/building hugo theme

### ISSUE THREAD

**Issue by autoferrit** [jbrodriguez/hugulp#15]
So, I am workign on a theme for my hugo site. And the files aren't watched by hugulp. I had started adding support for it but then realized you were parsing a config file already based on if someone specified an alternate config. I started with this in `reference.js`:

```javascript
var toml = require('toml-require').install({});
var configpath = path.join(path.resolve('./'), 'config.toml');
var tomlconfig = require(configpath);
var hugotheme = tomlconfig.theme
```

but you try to parse config files in `hugo.js` in the `hugo()` function.

The code above will properly get the `config.toml` in the root dir of the hugo app which is the default. And will properly get the theme. But I wanted to get your thoughts on how you would like to do this. Preferably I would like to have access to the theme name in the files that would handle those files. to watch the html/css/less/scss/js/whatever.

**Comment by jbrodriguez** [comment]
I haven't figured out yet how to properly support themes, but currently the build command will process the theme's assets (with some duplication, but the premise of optimization is still kept).

Your use case is a bit different, since you're actually developing a theme.

Your approach sounds ok, but you should do that in serve.js, which is where the watch(es) are created.

Maybe have a flag (--devTheme ??) defined to run that code only if needed ?

Does it make sense ?

**Comment by autoferrit** [comment]
well, theoretically, not that i think about it, we dont need to compile the html templates in the active theme do we since hugo will automatically handle that? Or am I wrong. The local layouts/templates are inherited from the theme and replaceable when you make one with the same name out of the theme. So are the assets the only thing we need to process anyways?

**Comment by autoferrit** [comment]
I suppose, if you're developing a theme you can do so in the root templates/static dirs and them move those to the theme when they're done. I'm still sorta new to hugo.

/shrugs

**Comment by jbrodriguez** [comment]
> we dont need to compile the html templates in the active theme do we since hugo will automatically handle that?

That's right :)

Actually, even the assets will be processed when you do a build, what's missing right now is watching for changes in the theme folder (while developing).

I'll play a bit with a theme and see what I find out.

In the worst case, I'll grab your code and do something along the lines of what I mentioned before (the --devTheme flag, etc.)

**Comment by ghost** [comment]
> I haven't figured out yet how to properly support themes

@jbrodriguez want me to spike a PR in that direction?

**Comment by jbrodriguez** [comment]
> @jbrodriguez want me to spike a PR in that direction?

Sure, I'd like to see what's your take on the matter.

**Comment by gour** [comment]
Any progress on this?

I'd like to have adequate setup for Hugo while developing/tweaking Hugo theme/site when using some CSS framework (e.g Bulma, Foundation...)

Any hint for that?

**Comment by jbrodriguez** [comment]
No progress so far, to be honest, as I'm tied up with other projects.

I remember I was thinking about adding another task that would process the theme folder as needed, but didn't go much further than that.

**Comment by gour** [comment]
> I remember I was thinking about adding another task that would process the theme folder as needed, but didn't go much further than that.

Does it mean that at the moment it's recommended to simply create a (Hugo) theme using theme's toolchain if one e.g. uses some CSS framework and **then** after finishing the theme use Hugolp for smaller tweakings or is it that Hugolp is simply better to be used for general assets, iow. not suitable for working with themes?

**Comment by jbrodriguez** [comment]
If you're using a theme for your site (not creating one), the theme assets should get processed by the hugulp pipeline.

**Comment by saschalalala** [comment]
Wouldn't adding watch support to themes not just only mean to load the theme name inside serve.js and watch the theme directories? Would I have to reparse the config file inside serve.js or would it be better to create a global config object that can be used inside the tasks?
