### ISSUE TITLE
Typo, use styles.css rather than style.css to link to CSS

### ISSUE THREAD

**Issue by martinsanders** [jbrodriguez/hugulp#16]
After some research I found that the linked docs have a typo. You need to use the following code to link to the rendered style-sheet.

<link rel="stylesheet" href="css/styles.css">

**Comment by jbrodriguez** [comment]
hi @martinsanders , not sure what you mean.
Could you please clarify ?

**Comment by ghost** [comment]
@martinsanders think you could send in a PR to fix this?
