### ISSUE TITLE
Integrate hugo-bin

### ISSUE THREAD

**Issue by ghost** [jbrodriguez/hugulp#18]
Like #17, but without the automatic download (what he really wants is Docker for a prepackaged environment).

Should remove quite a bit of the code and help work your way out of Gulp.

https://github.com/fenneclab/hugo-bin

**Comment by jbrodriguez** [comment]
After #17 was opened, I started looking at some hugo wrappers, hugo-bin among them.
Hadn't thought about a docker, seems like something doable.


> Should remove quite a bit of the code and help work your way out of Gulp.
Not sure why you'd think it would remove that much code.

You think webpack would be a better fit than gulp ?

**Comment by ghost** [comment]
> Not sure why you'd think it would remove that much code.

I was looking at the existing wrapper. Looked involved. Just my off the cuff interpretation.

> You think webpack would be a better fit than gulp ?

I prefer my build pipelines to bring heavy opinion and limit deps/complexity whereever possible. Webpack is one of those areas where I feel the complexity indroduced quickly becomes a slippery slope for given its general lack of opinion. (Disclaimer: I have [strong bias](https://medium.com/@jhabdas/webpack-is-your-achilles-heel-d3cd80821a4f) here.)

**Comment by ghost** [comment]
Some possible alternatives to Webpack:
https://github.com/lasso-js/lasso - Node
https://github.com/jhabdas/fetch-inject - Browser

**Comment by jbrodriguez** [comment]
Thanks!

Although I still need to wrap my head around fetch-inject, I'll look deeper into both.

**Comment by ghost** [comment]
@jbrodriguez groovy. if you have any questions about `fetch-inject` just lmk. I just updated the docs, too and implemented it in my first client site. it's faaaaaaaaaaast (and a whopping ~600 B).
