### ISSUE TITLE
[discussion] Dropping LESS support

### ISSUE THREAD

**Issue by ghost** [jbrodriguez/hugulp#19]
Why have both? libsass is a rockstar. and libs like susy and breakpoint make authoring CSS with SASS a dream come true. plus most Jekyll sites use SASS, so there's a good reason to bring the opinion IMHO.

**Comment by jbrodriguez** [comment]
I use sass exclusively, but I've dealt with some projects using less.
It's not that expensive to support it, so .. why not ? :)
