### ISSUE TITLE
Use standard linter

### ISSUE THREAD

**Issue by ghost** [jbrodriguez/hugulp#21]
Sorry for the barrage of issues. Just discovering this asset pipeline and respect the vision (and scope). For JS linting, what are your thoughts on moving towards Standard?

https://github.com/emgeee/gulp-standard

**Comment by jbrodriguez** [comment]
Hi @jhabdas, thanks for the comments, you brought up some interesting topics.
Sure, I started using standard in one of my projects, it makes sense.
