### ISSUE TITLE
Combine Clean CSS and Autoprefixer

### ISSUE THREAD

**Issue by ghost** [jbrodriguez/hugulp#22]
https://github.com/danielhusar/gulp-pleeease

Thoughts?

**Comment by jbrodriguez** [comment]
Had not seen it before, it's kept up to date.

I'll check it out.

**Comment by ghost** [comment]
I shouldn't have opened this. It looks like Pleeease hasn't advanced in the way I'd expected since it was introduced. And per the docs it says Sass and LESS support are still _experimental_, and that just won't do.
