### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by eyedol** [jbrodriguez/hugulp#23]
Spinning this off a docker image will ease a lot of setup and deployment efforts. I don't have to install node and npm stuff on my host machine. Would help hugely with teams when it comes to development collaboration. Alas, but it's working on my machine!

I opened a [PR](https://github.com/netlify/victor-hugo/pull/25) a few days ago in a similar project but the maintainers find it not aligning with the project's goal of keeping it simple( which I understand ). Reading through the comments on #18 it seems there's an interest in adding docker support. Let me know if you welcome a PR for this. I'll open one right away.

**Comment by jbrodriguez** [comment]
@eyedol, sure !

I'd appreciate a PR for this 👍
