### ISSUE TITLE
Stuck in infinite loop on Ubuntu

### ISSUE THREAD

**Issue by mistermantas** [jbrodriguez/hugulp#26]
![selection_253](https://user-images.githubusercontent.com/11616378/29210008-1bcdc91e-7e9a-11e7-9ec9-dedac5aaef20.png)

Probably my fault, since “root” doesn’t have access to `node-sass` for some reason… But for good measure, I’m still reporting the issue, in case it has something to do with hugulp.

**Comment by jbrodriguez** [comment]
hi @mistermantas , did you install it as root or as a regular user ?

**Comment by mistermantas** [comment]
As root.

**Comment by jbrodriguez** [comment]
I see.

I'm pretty sure this isn't an issue with hugulp itself.

I haven't tested on linux, but on my mac I install it as a regular user without problems.

In any case, it's strange that root wouldn't have access to any folder, especially those non-system folders.

Can you try installing as a regular user ?

I'm not really an expert in node environment issues 😮

**Comment by mistermantas** [comment]
Regular user never works. I think my environment is just broken. If you have no clue what else this could be, I’ll close the issue.
