### ISSUE TITLE
UnCSS support

### ISSUE THREAD

**Issue by gour** [jbrodriguez/hugulp#27]
While looking at Foundation framework I see that it uses UnCSS to trim the final CSS from the unused CSS selectors which looks quite nice when optimizing assets' size, so I wonder what do you think about including support for UnCSS in Hugulp or it is already possible to do it easily?

**Comment by jbrodriguez** [comment]
hugulp is currently using clearcss.

Can't remember if uncss only removes unused styles or minifies as well.

If it's the former, it would be very simple to use both. If it's the later, it would mean a decision of dropping one in favor of the other.

**Comment by gour** [comment]
> Can't remember if uncss only removes unused styles or minifies as well.

Acccording to the [docs](https://github.com/giakki/uncss): "UnCSS is a tool that removes unused CSS from your stylesheets."

> If it's the former, it would be very simple to use both. 

Any hint considering I'm total noob when it comes to that JS-builders... :-(

**Comment by jbrodriguez** [comment]
You would need to install uncss, then change the styles gulp task, to invoke uncss before [this line](https://github.com/jbrodriguez/hugulp/blob/master/gulp/styles.js#L23)
