### ISSUE TITLE
Source Map

### ISSUE THREAD

**Issue by senden9** [jbrodriguez/hugulp#28]
Hi!
Is there some way to enable source maps? I would it use for for CSS/SCSS.

Best Regards

**Comment by jbrodriguez** [comment]
I didn't there were sourcemaps for scss/css :)

I just checked [the npm page](https://www.npmjs.com/package/gulp-sass) for gulp-sass, which is the plugin doing sass-to-css conversion.

It doesn't look too difficult to implement (somewhere near [this line](https://github.com/jbrodriguez/hugulp/blob/master/gulp/styles.js#L14))

I always welcome a PR :)

**Comment by saschalalala** [comment]
If this is going to be implemented, also make it configurable and use false as a sane default.
