### ISSUE TITLE
HTML minifying

### ISSUE THREAD

**Issue by saschalalala** [jbrodriguez/hugulp#30]
Hugo creates some artifacts (for example empty `<p>` elements) and a lot of unnecessary whitespace (can be deleted using `{{- foo -}}`) when compiling HTML. I created an additional task and command that uses https://github.com/jonschlinkert/gulp-htmlmin for cleaning the html. I am going to create a pull request soon.

In order not to not interfere with existing scripts I did not integrate it in the default build process. This way a user can do the following:

`hugulp build && hugulp minifyhtml`

**Comment by jbrodriguez** [comment]
Thanks for the PR !
