### ISSUE TITLE
.hugulprc

### ISSUE THREAD

**Issue by saschalalala** [jbrodriguez/hugulp#32]
Wouldn't it be nice to have a hugulp config file? Some things that could be configured on a project base from my point of view:

  * linter: eslint/jshint/standard
  * minifyhtml: true/false
  * uncss: true/false(see #27, would also need general uncss support)

**Comment by jbrodriguez** [comment]
Seems a good idea, I'll think about it.

As a matter of fact, I've been looking into replacing gulp entirely with a golang based setup (https://github.com/jbrodriguez/hugulp/issues/20#issuecomment-341893452), but there are many components that just work (™️) on node.

I'm looking at another approach still based on gulp, but that would make it more flexible, I'll try to  flesh it out the next couple of days.

**Comment by hanzei** [comment]
This issue seams to be resolved with the release of version 2.0
