### ISSUE TITLE
hugulp next

### ISSUE THREAD

**Issue by jbrodriguez** [jbrodriguez/hugulp#38]
This is the proposal for the next version of hugulp.

Currently, hugulp depends on node.js, isn't easily configurable and doesn't play nice with themes.

I looked into having a binary built in Go, to run all the tasks, so that no dependencies were required.

But the fact remains that nodejs has the best ecosystem of readily available plugins/libraries for sass/less preprocessing, image optimization, etc., so it's difficult to move away.

Nevertheless, while looking into the matter, I became aware that a better architecture would be to make hugulp a post-processor of hugo !

Do whatever you want with hugo, install/customize any themes, use hugo built-in watching for hot reloading.

When you're ready to publish the site invoke hugo, then hugulp to optimize the site hugo built. Something like:
- hugo && hugulp build

hugulp will process the public folder, running the asset pipeline.

This pipeline is defined in the config file (.hugulprc as per @saschalalala suggestion), so if maybe you don't want to fingerprint the assets, just remove the corresponding task(s) from the pipeline field of the config.

This would work extremely well, weren't for sass/lees and probably babel/js pre-processing.

So, hugulp watch needs to live on, to make those conversions.

The [hugulp next](https://github.com/jbrodriguez/hugulp/tree/next) branch is an implementation of this concept.

This is a sample .hugulprc

```json
{
	"pipeline": ["images", "styles", "revision", "reference", "minifyhtml"],
	"path": {
		"styles": "css",
		"images": "img",
		"scripts": "js"
	},
	"watch": {
		"source": "assets",
		"target": "static"
	},
	"build": {
		"source": "public",
		"target": "public"
	},
	"autoprefixer": { "browsers": ["last 2 versions"] },
	"cleancss": { "advanced": false },
	"htmlmin": { "collapseWhitespace": true, "removeEmptyElements": true }
}
```

Some thought needs to be given to alternate plugins: uncss instead of cleancss, etc.

Although it works pretty well, as per my tests, still needs more polishing, remove some duplication, delete public folder before invocation and probably review a couple of decisions.

Let me know what you think !

@saschalalala @jhabdas @eyedol @autoferrit @jaydreyer 

Ref #28 #32 #27 #35 #20 #15

**Comment by hanzei** [comment]
Hey @ @jbrodriguez
Thank your for the work you put into this project. hugulp really makes working with hugo easier.

As far as I have understand version 2 is already published and most of the topics you brought up in this issue are resolved. Is this correct? Do you need more feedback?
