### ISSUE TITLE
JavaScript Concatenation?

### ISSUE THREAD

**Issue by prime31** [jbrodriguez/hugulp#41]
The README says:

> The main idea is to recreate the famous Ruby on Rails Asset Pipeline, which minifies, concatenates and fingerprints the assets used in your website.

I can't seem to figure out how to get JavaScript concatenation working. Compressing and fingerprinting are working fine but not concatenation. Is there something undocumented that allows this?

**Comment by jbrodriguez** [comment]
If you're using the default .hugulprc, try putting your js files in assets/scripts.

Does that work ?

**Comment by prime31** [comment]
That is what I was doing and it just seems to jslint the files and copy them in static/scripts but not concat them.
<img width="221" alt="screen shot 2018-03-27 at 2 06 48 pm" src="https://user-images.githubusercontent.com/60377/37995074-2cd3fbd4-31c8-11e8-82a6-82e0229d3209.png">

**Comment by jbrodriguez** [comment]
You know what, you're absolutely right.

In watch mode, it does jshint only.

In build mode, It's uglifying each individual file, but it's not concatenating it.

I'll probably have some time to fix it by the weekend.

It's a small change

```diff
    .pipe(uglify())
+   .pipe(concat('scripts.js'))
    .pipe(size({ title: 'scripts: ' }))
```

right around here

https://github.com/jbrodriguez/hugulp/blob/master/gulp/build.js#L91

**Comment by prime31** [comment]
Bingo. Works like a champ! Thanks! If I wasnt such a Node/Gulp newbie I would have found that myself! I assume that this will just concat in filename order.

Totally unrelated but it would be a pretty nice feature to be able to have it work like scss files: an underscore in the filename ignores it and then a script with includes makes ordering the files nice and simple.
