### ISSUE TITLE
hugulp reprocesses images already compressed or optimized by hugulp

### ISSUE THREAD

**Issue by kenthunt** [jbrodriguez/hugulp#46]
When running hugulp, if selecting or setting:

  "pipeline": [
    **"images",**
    "styles",
    "scripts",
    "fingerprint",
    "html"
  ],

in the .hugulprc config file than, every time you build the site it will reprocess the **images**, even if they have not changed. Since this is quite cpu intensive and non-trivial for a large amount of images I suggest that the image should be hashed with _shasum -a 512 image.jpg_ and the image stored in a processed folder that is checked when rerunning hugulp. This might be a better process for all the minification steps. Process once, reuse the results which should be bit for bit accurate if starting with the same input file.

**Comment by jbrodriguez** [comment]
Thanks for the input !

If you happen to work on it, I'm happy to accept a PR :)
