### ISSUE TITLE
No stylesheets generated?

### ISSUE THREAD

**Issue by bobcat4848** [jbrodriguez/hugulp#47]
I'm trying to use scss with my project and have followed the installation process line by line and my page is still not being styled correctly. 

```
  "path": {
    "styles": "styles",
    "images": "images",
    "scripts": "scripts"
  },
  "watch": {
    "source": "resources",
    "target": "static"
  },
```

Nothing is being written to the static folder, it is remaining empty. I thought it takes my scss from my resources/styles folder and turns it into css to my static folder. Why is it not doing this?

https://i.imgur.com/vUW9E2B.jpg

**Comment by jbrodriguez** [comment]
If you're not doing it ... you need to run hugulp watch, so that scss files are monitored for changes and converted accordingly

https://github.com/jbrodriguez/hugulp#getting-started

**Comment by bobcat4848** [comment]
Okay, yes that fixed it. Thank you.

How come it generates one huge css file? That can get hard to manage. Is there anything I can put in the configuration file to generate separate minified css files?

**Comment by jbrodriguez** [comment]
no, there's no such config option.
