### ISSUE TITLE
Hugo now uses config.toml by default

### ISSUE THREAD

**Issue by mgamini** [jbrodriguez/hugulp#9]
New users will be unable to build, as Hugo creates a .toml file instead of a .yaml file.

**Comment by jbrodriguez** [comment]
wow ! Ok, thanks @mgamini , I should honestly use hugo defaults, let me check how to fix it in the next few days ...

**Comment by jbrodriguez** [comment]
closed by 57b3f08846f23eb3f833dd58cc20868f8b4e8294
